service: ohchofitness-api

plugins:
  - '@haftahave/serverless-ses-template'

package:
  exclude:
    - node_modules/**
    - test/**

provider:
  name: aws
  profile: ${self:custom.profiles.${opt:stage, self:provider.stage, 'development'}}
  stage: ${opt:stage, 'development'}
  runtime: nodejs20.x
  iam:
    role: arn:aws:iam::401327758731:role/ocho-fitness-api

functions:
  scheduleSession:
    handler: handler.scheduleSession
    events:
      - http:
          path: schedule-session
          method: post
          cors: true
    environment: ${file(env.${opt:stage, self:provider.stage}.json)}
  contactForm:
    handler: handler.contactForm
    events:
      - http:
          path: contact-form
          method: post
          cors: true
    environment: ${file(env.${opt:stage, self:provider.stage}.json)}

custom:
  profiles:
    development: ochofitness
    staging: ochofitness
    production: ochofitness
  sesTemplates:
    addStage: true                             # Specifies whether to add stage to template name (default false)
    configFile: './email-templates.js' # Config file path (default './ses-email-templates/index.js')
    disableAutoDeploy: true                    # Specifies whether to sync templates while sls deploy (default false)
    region: 'us-east-1'                        # Specifies AWS region for SES templates (not required)
